#!/usr/bin/env bash
# Script that install Nginx and configures a simple default page.
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo Holberton School | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
